[2025-05-20T06:28:21.275+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-20T06:28:21.319+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-20T05:00:00+00:00 [queued]>
[2025-05-20T06:28:21.334+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-20T05:00:00+00:00 [queued]>
[2025-05-20T06:28:21.335+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-20T06:28:21.357+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): check_if_retrain_needed> on 2025-05-20 05:00:00+00:00
[2025-05-20T06:28:21.365+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_PWU', 'check_if_retrain_needed', 'scheduled__2025-05-20T05:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/monitor_PWU.py', '--cfg-path', '/tmp/tmprr8_v38g']
[2025-05-20T06:28:21.368+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask check_if_retrain_needed
[2025-05-20T06:28:21.369+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=532) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-20T06:28:21.370+0000] {standard_task_runner.py:63} INFO - Started process 533 to run task
[2025-05-20T06:28:21.415+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-20T05:00:00+00:00 [running]> on host 0bc9c459f625
[2025-05-20T06:28:21.510+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_PWU' AIRFLOW_CTX_TASK_ID='check_if_retrain_needed' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-20T05:00:00+00:00'
[2025-05-20T06:28:21.511+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-20T06:28:21.525+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-05-20T06:28:21.537+0000] {python.py:237} INFO - Done. Returned value was: trigger_retrain
[2025-05-20T06:28:21.538+0000] {branch.py:36} INFO - Branch into trigger_retrain
[2025-05-20T06:28:21.539+0000] {skipmixin.py:178} INFO - Following branch trigger_retrain
[2025-05-20T06:28:21.557+0000] {skipmixin.py:246} INFO - Skipping tasks [('end', -1)]
[2025-05-20T06:28:21.588+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-20T06:28:21.611+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=monitor_PWU, task_id=check_if_retrain_needed, execution_date=20250520T050000, start_date=20250520T062821, end_date=20250520T062821
[2025-05-20T06:28:21.664+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-20T06:28:21.691+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-20T06:28:21.696+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
