[2025-05-17T08:44:01.495+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-17T08:44:01.530+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_PWU.monitor_model manual__2025-05-17T08:44:00.472747+00:00 [queued]>
[2025-05-17T08:44:01.540+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_PWU.monitor_model manual__2025-05-17T08:44:00.472747+00:00 [queued]>
[2025-05-17T08:44:01.541+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-17T08:44:01.559+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): monitor_model> on 2025-05-17 08:44:00.472747+00:00
[2025-05-17T08:44:01.567+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_PWU', 'monitor_model', 'manual__2025-05-17T08:44:00.472747+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/monitor_PWU.py', '--cfg-path', '/tmp/tmp1kzx4ova']
[2025-05-17T08:44:01.569+0000] {standard_task_runner.py:91} INFO - Job 291: Subtask monitor_model
[2025-05-17T08:44:01.570+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1137) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-17T08:44:01.571+0000] {standard_task_runner.py:63} INFO - Started process 1138 to run task
[2025-05-17T08:44:01.621+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_PWU.monitor_model manual__2025-05-17T08:44:00.472747+00:00 [running]> on host a5e636d29f18
[2025-05-17T08:44:01.715+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_PWU' AIRFLOW_CTX_TASK_ID='monitor_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-17T08:44:00.472747+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-17T08:44:00.472747+00:00'
[2025-05-17T08:44:01.716+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-17T08:44:01.783+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-17T08:44:01.783+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/monitor_PWU.py", line 22, in monitor_model
    raise Exception("Flask prediction failed.")
Exception: Flask prediction failed.
[2025-05-17T08:44:01.794+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=monitor_PWU, task_id=monitor_model, execution_date=20250517T084400, start_date=20250517T084401, end_date=20250517T084401
[2025-05-17T08:44:01.807+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 291 for task monitor_model (Flask prediction failed.; 1138)
[2025-05-17T08:44:01.825+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-17T08:44:01.850+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-17T08:44:01.854+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
