[2025-05-17T14:00:13.863+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-17T14:00:13.894+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-17T14:00:13.233658+00:00 [queued]>
[2025-05-17T14:00:13.901+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-17T14:00:13.233658+00:00 [queued]>
[2025-05-17T14:00:13.902+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-17T14:00:13.915+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): train_PWU> on 2025-05-17 14:00:13.233658+00:00
[2025-05-17T14:00:13.921+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'retrain_PWU_dag', 'train_PWU', 'manual__2025-05-17T14:00:13.233658+00:00', '--job-id', '363', '--raw', '--subdir', 'DAGS_FOLDER/retrain_PWU_dag.py', '--cfg-path', '/tmp/tmp0iucaz8p']
[2025-05-17T14:00:13.922+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12273) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-17T14:00:13.923+0000] {standard_task_runner.py:91} INFO - Job 363: Subtask train_PWU
[2025-05-17T14:00:13.923+0000] {standard_task_runner.py:63} INFO - Started process 12274 to run task
[2025-05-17T14:00:13.966+0000] {task_command.py:426} INFO - Running <TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-17T14:00:13.233658+00:00 [running]> on host b91ac73f2b68
[2025-05-17T14:00:14.046+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='retrain_PWU_dag' AIRFLOW_CTX_TASK_ID='train_PWU' AIRFLOW_CTX_EXECUTION_DATE='2025-05-17T14:00:13.233658+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-17T14:00:13.233658+00:00'
[2025-05-17T14:00:14.047+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-17T14:00:14.061+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-17T14:00:14.062+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/train_PWU.py']
[2025-05-17T14:00:14.070+0000] {subprocess.py:86} INFO - Output:
[2025-05-17T14:08:42.480+0000] {subprocess.py:93} INFO - [Epoch 1] Loss: 0.0097
[2025-05-17T14:08:42.480+0000] {subprocess.py:93} INFO - [✅ Saved] Trained model → /models/PWU/model.pth
[2025-05-17T14:08:43.055+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-17T14:08:43.056+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-17T14:08:43.081+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=retrain_PWU_dag, task_id=train_PWU, execution_date=20250517T140013, start_date=20250517T140013, end_date=20250517T140843
[2025-05-17T14:08:43.139+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-17T14:08:43.157+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-17T14:08:43.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
